- name: Create Jenkins Image
  hosts: all
  remote_user: ec2-user
  become: true
  become_method: sudo
  roles:
    - disable-selinux
    - upgrade-all-packages
    - install-development-tools
    - install-jdk
    - install-jenkins